
# Language Dictionaries

STRINGS = {
    "KO": {
        "title": "Young & Home - 청년 주거 AI",
        "header_title": "Young & Home",
        "header_subtitle": "AI 기반 청년 주거 안심 파트너",
        "menu_home": "홈",
        "menu_search": "스마트 매물 검색",
        "menu_safety": "등기부 위험 분석",
        "menu_neg": "협상 도우미",
        "menu_legal": "법률 상담",
        "menu_monitor": "권리 변동 알림",
        "menu_profile": "내 프로필",
        "menu_checklist": "체크리스트",
        "menu_report": "종합 리포트",
        "lang_settings": "언어 설정",
        "sidebar_option_ko": "한국어",
        "sidebar_option_en": "English",
        "user_profile": "사용자 프로필",
        "user_name": "김서강",
        "user_info": "대학생 | 자산: 2,000만원",
        "home_welcome": "반갑습니다, 서강님 👋",
        "home_desc": "나만의 주거 안심 에이전트가 준비되었습니다.",
        "badge_new": "새 매물 3건",
        "badge_system": "시스템 정상",
        "card_discovery": "탐색된 매물",
        "card_discovery_desc": "개의 매물 발견",
        "card_discovery_sub": "통근 시간 시뮬레이션 중...",
        "card_safety": "안전 진단",
        "card_safety_desc": "개의 위험 신호",
        "card_safety_sub": "실시간 모니터링 중",
        "quick_actions": "빠른 실행",
        "btn_start_search": "매물 찾기",
        "btn_analyze": "계약서 분석",
        "btn_calc": "월세 계산기",
        "search_title": "스마트 매물 검색",
        "search_desc": "정부 혜택과 연동된 최적의 주거를 찾아드려요.",
        "search_pref": "선호 조건 (Preferences)",
        "label_loc": "위치",
        "ph_loc": "예: 마포구, 신촌",
        "label_maxtime": "최대 통근 시간 (분)",
        "label_budget": "보증금 한도 (만원)",
        "label_monthly": "월세 한도 (만원)",
        "search_user_info": "사용자 정보",
        "label_age": "나이",
        "label_status": "신분",
        "status_options": ["대학생", "직장인", "취업준비생", "창업자"],
        "search_benefit": "혜택 필터링",
        "check_public": "공공임대 (SH/LH/행복주택)",
        "check_loan": "청년 전월세 보증금 대출",
        "check_support": "청년 월세 지원 사업",
        "btn_run_agent": "AI 매물 & 혜택 검색",
        "progress_rag": "RAG 데이터베이스 검색 중...",
        "progress_benefit": "맞춤형 혜택 정보 매칭 중",
        "progress_finalize": "최종 리포트 생성 중...",
        "result_analyzed": "분석 결과",
        "map_view": "🗺️ 매물 지도 보기",
        "map_info": "📍 지도에 {count}개의 매물이 표시되었습니다.",
        "map_empty": "조건에 맞는 매물 위치 정보가 없습니다.",
        "safety_title": "등기부 위험 분석",
        "safety_desc": "계약 전, 깡통전세/전세사기 위험을 진단합니다.",
        "upload_card_title": "분석할 문서 선택",
        "upload_card_desc": "등기부등본 PDF 또는 이미지를 업로드하세요",
        "sample_select": "샘플 매물 선택",
        "sample_options": ["파일 업로드", "안전 매물 (데모)", "위험 매물 (데모)", "보통 매물 (데모)"],
        "label_deposit": "예정 보증금 (만원)",
        "btn_safety_start": "위험도 분석 시작",
        "status_extract": "데이터 추출 중...",
        "status_verify": "권리 관계 분석 중...",
        "status_calc": "위험 점수 산출 중...",
        "neg_title": "협상 에이전트",
        "neg_desc": "어려운 집주인과의 대화, AI가 대신 작성해드립니다.",
        "label_topic": "협상 주제",
        "topic_options": ["보증보험 가입 요청", "특약 조항 추가", "수리 요청", "계약 조건 변경", "보증금 반환 촉구"],
        "label_sender": "보내는 사람",
        "label_context": "추가 상황 설명",
        "ph_context": "예: 집주인이 해외 거주 중이라 연락이 잘 안됩니다.",
        "btn_draft": "메시지 초안 생성",
        "mon_title": "권리 변동 파수꾼",
        "mon_desc": "내 보증금을 지키는 24시간 등기 모니터링",
        "mon_active": "실시간 감시 중",
        "mon_time": "매일 오전 09:00 자동 조회",
        "mon_target": "모니터링 대상",
        "btn_edit_profile": "프로필 수정",
        "label_name": "이름",
        "label_assets": "자산 (만원)",
        "label_name_input": "이름",
        "label_status_input": "신분",
        "label_assets_input": "자산",
        "btn_save": "저장",
        "msg_updated": "업데이트 완료!",
        "footer_made_by": "Team Young & Home 제작",
    },
    "EN": {
        "title": "Young & Home - AI Housing Agent",
        "header_title": "Young & Home",
        "header_subtitle": "AI-Powered Housing Guardian",
        "menu_home": "Home",
        "menu_search": "Smart Search",
        "menu_safety": "Safety Scan",
        "menu_neg": "Negotiator",
        "menu_legal": "Legal Help",
        "menu_monitor": "Monitoring",
        "menu_profile": "My Profile",
        "menu_checklist": "Checklist",
        "menu_report": "Full Report",
        "lang_settings": "Language Settings",
        "sidebar_option_ko": "Korean",
        "sidebar_option_en": "English",
        "user_profile": "User Profile",
        "user_name": "Seogang Kim",
        "user_info": "Student | Assets: 20M KRW",
        "home_welcome": "Hello, Seogang 👋",
        "home_desc": "Your personal housing agent is ready.",
        "badge_new": "3 New Matches",
        "badge_system": "System Operational",
        "card_discovery": "Discovery",
        "card_discovery_desc": " listings found",
        "card_discovery_sub": "Simulating commute times...",
        "card_safety": "Safety Scan",
        "card_safety_desc": " alert detected",
        "card_safety_sub": "Monitoring active",
        "quick_actions": "Quick Actions",
        "btn_start_search": "Start Search",
        "btn_analyze": "Analyze Doc",
        "btn_calc": "Calculators",
        "search_title": "Smart Search",
        "search_desc": "Finding optimum housing with government benefits.",
        "search_pref": "Preferences",
        "label_loc": "Location",
        "ph_loc": "e.g. Mapo-gu, Sinchon",
        "label_maxtime": "Max Commute (min)",
        "label_budget": "Deposit Limit (10k KRW)",
        "label_monthly": "Rent Limit (10k KRW)",
        "search_user_info": "User Info",
        "label_age": "Age",
        "label_status": "Status",
        "status_options": ["Student", "Worker", "Job Seeker", "Entrepreneur"],
        "search_benefit": "Benefit Filtering",
        "check_public": "Public Housing (SH/LH)",
        "check_loan": "Youth Loan Support",
        "check_support": "Monthly Rent Support",
        "btn_run_agent": "Run Agent",
        "progress_rag": "Querying Knowledge Base...",
        "progress_benefit": "Matching Welfare Benefits...",
        "progress_finalize": "Finalizing Report...",
        "result_analyzed": "Analyzed Options",
        "map_view": "🗺️ Map View",
        "map_info": "📍 Showing {count} listings on map.",
        "map_empty": "No location data available for listings.",
        "safety_title": "Safety Scan",
        "safety_desc": "Analyze contracts & registry for fraud risks.",
        "upload_card_title": "Upload Documents",
        "upload_card_desc": "Supports PDF, PNG, JPG (Registry, Contract)",
        "sample_select": "Select Sample",
        "sample_options": ["Upload File", "Safe Listing (Demo)", "Risky Listing (Demo)", "Moderate (Demo)"],
        "label_deposit": "Exp. Deposit (10k KRW)",
        "btn_safety_start": "Start Risk Analysis",
        "status_extract": "Extracting Data...",
        "status_verify": "Verifying Rights...",
        "status_calc": "Calculating Risk...",
        "neg_title": "Negotiator Agent",
        "neg_desc": "AI drafting professional negotiation messages.",
        "label_topic": "Select Topic",
        "topic_options": ["Insurance Request", "Add Special Clause", "Repair Request", "Contract Modification", "Deposit Return Demand"],
        "label_sender": "Sender Name",
        "label_context": "Context",
        "ph_context": "e.g. Landlord is overseas...",
        "btn_draft": "Draft Message",
        "mon_title": "Registry Guard",
        "mon_desc": "24/7 Watchdog for your property rights.",
        "mon_active": "Active Monitoring",
        "mon_time": "Checking daily at 09:00 AM",
        "mon_target": "Target Address",
        "btn_edit_profile": "Edit Profile",
        "label_name": "Name",
        "label_assets": "Assets (10k KRW)",
        "label_name_input": "Name",
        "label_status_input": "Status",
        "label_assets_input": "Assets",
        "btn_save": "Save",
        "msg_updated": "Updated!",
        "footer_made_by": "Made with ❤️ by Team Young & Home",
    }
}
